name = "mint-works"
main = "src/index.ts"
compatibility_date = "2023-04-04"

[env.stg]
name = "mint-works-stg"

[env.prd]
name = "mint-works"

[vars]
# The necessary secrets are:
# - 
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
ENVIRONMENT = "stg"

[env.stg.vars]
ENVIRONMENT = "stg"

[env.prd.vars]
ENVIRONMENT = "prd"
